In [74]:
import numpy as np
from itertools import product
from scipy import signal

In [75]:
n=4
k=2

In [76]:
all_matrices = np.array(list(product([0,1], repeat=2*n)))
all_matrices=all_matrices.reshape((-1,2,n))

In [77]:
filter=np.ones((1,1,k))

In [78]:
print(all_matrices)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 1]]

 [[0 0 0 0]
  [0 0 1 0]]

 ...

 [[1 1 1 1]
  [1 1 0 1]]

 [[1 1 1 1]
  [1 1 1 0]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [79]:
out_1=signal.fftconvolve(all_matrices, filter, mode='valid',axes=2).astype(int)

In [80]:
print(out_1.shape)

(256, 2, 3)


In [83]:
print(all_matrices[0,:,:])
print(all_matrices[1,:,:])
print(all_matrices[2,:,:])

[[0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 1]]
[[0 0 0 0]
 [0 0 1 0]]


In [84]:
print(out_1[0,:,:])
print(out_1[1,:,:])
print(out_1[2,:,:])

[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 1]]
[[0 0 0]
 [0 1 1]]
